basePath: /
definitions:
  models.Order:
    properties:
      created_at:
        type: string
      id:
        type: integer
      item:
        type: string
      nickname:
        type: string
      price:
        type: number
      quantity:
        type: integer
      size:
        type: string
      status:
        type: string
      total_price:
        type: number
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.PaymentRequest:
    properties:
      amount:
        description: Valor do pagamento
        type: number
      created_at:
        description: Data e hora da criação da solicitação
        type: string
      id:
        type: integer
      method:
        description: Método de pagamento (cartão, boleto, etc.)
        type: string
      order_id:
        description: ID do pedido associado a esta solicitação de pagamento
        type: integer
      status:
        description: Status do pagamento (pendente, pago, falhado)
        type: string
      updated_at:
        description: Data e hora da última atualização
        type: string
    type: object
  models.User:
    properties:
      id:
        type: integer
      role:
        description: '"admin" ou "customer"'
        type: string
      username:
        type: string
    type: object
  order_controllers.UpdateOrderStatusRequest:
    properties:
      status:
        type: string
    required:
    - status
    type: object
host: localhost:8080
info:
  contact:
    email: suporte@seusite.com
    name: Suporte da API
    url: http://www.seusite.com/support
  description: API para gerenciamento de produtos, pedidos e usuários.
  title: API de Vendas
  version: "1.0"
paths:
  /create_order/:
    post:
      consumes:
      - application/json
      description: Cria um pedido com base nos dados enviados no corpo da requisição
      parameters:
      - description: Dados do Pedido
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo pedido
      tags:
      - Orders
  /list-orders/:
    get:
      consumes:
      - application/json
      description: Retorna a lista de todos os pedidos cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pedidos
      tags:
      - Orders
  /process-payment/:
    post:
      consumes:
      - application/json
      description: Processa o pagamento para um pedido específico com base nos dados
        fornecidos
      parameters:
      - description: Dados do Pagamento
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/models.PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Processa o pagamento
      tags:
      - Orders
  /update-order-status/{order_id}/:
    put:
      consumes:
      - application/json
      description: Atualiza o status do pedido identificado pelo ID
      parameters:
      - description: ID do Pedido
        in: path
        name: order_id
        required: true
        type: integer
      - description: Novo status do pedido
        in: body
        name: status
        required: true
        schema:
          $ref: '#/definitions/order_controllers.UpdateOrderStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualiza o status do pedido
      tags:
      - Orders
swagger: "2.0"
